###############################################################################################################
###############################################################################################################
## Graphing functions for easyR_TREES
## version 1.1
## 28122020
## Mitchell Hitchcock
## mchitchc@buffalo.edu
## 
## Description:
## These are the functions for generating graphs of the outputs generated by TREES through easyR_TREES.
## Modifications should be restricted to ggplot themes and file saving methods to avoid breaking the functions.
###############################################################################################################
###############################################################################################################

##################################Load required packages#######################################################
# List of required packages
pkgli<-c("crayon","dplyr","tidyr","readr","readxl","withr","ggplot2","ggthemes",
         "extrafont","parallel","foreach","doParallel","plotly","scales","Cairo")
## Some of these may not be required at all times so if you have a compatibility issue
## try removing the problematic package from here.
## For example plotly and htmlwidgets have issues on CCR and are not necessary for current
## format of the functions.

# Load or install missing packages
for(pa in pkgli){
  if (!require(pa,character.only=TRUE)){
    install.packages(pa,character.only=TRUE)
  }else{}
  library(pa,character.only=TRUE)
}



########################################### Plot Leaf_areas ###################################################



Leaf_Area_Plot<-function(Result_Dest=paste(getwd(),"/easyR_TREES/Outputs",sep=""),#Where TREES output results to.
                         Which_Parameter="microbiomeScalar",
                         New_values=c(1),
                         Use_Gamma=FALSE,
                         Itter=NULL,#number of iterations ran. (Only applies if Use_Gamma is TRUE)
                         Drivers="cc_ww_drivers_drought_validation",#Vector of driver names as characters
                         Figure_title=NULL,#Optional
                         Compare_to=NULL,#dataframe containing Jday, block, Leaf_number, and Leaf_Area
                         Smooth_on=FALSE#Plot useing geom_smooth instead of boxplot? (TRUE or FALSE)
){
  
  
  if(is.null(Figure_title)){
    Figure_title<-Which_Parameter
  }
  if(is.null(New_values)){
    New_values<-0
  }
  if(is.null(Itter)){
    Itter<-0
  }
  
  dir.create(paste(Result_Dest,"/Figures",sep=""),recursive = T)
  
  for(i in Drivers){
    Data_in<- data.frame() 
    for(j in Itter){
      for(k in New_values){
        
        Data_in<-rbind(Data_in,
                       read_delim(paste(Result_Dest,"/",Which_Parameter,"/",i,"/",Which_Parameter,k,"itter",j,".leaf",sep=""),"\t") %>% 
                         separate(col = ti, into = c("toss", "Jday","Hour","Min"),convert=TRUE)%>% 
                         mutate(Jday=Jday+((Hour+(Min/100))/24)) %>% 
                         dplyr::select(-toss,-Hour,-Min)  %>% 
                         gather(key=Leaf_number,value=Leaf_Area,-Jday)%>% 
                         mutate(NewValue=k,Itteration=j) %>% 
                         filter(!is.na(Leaf_Area))
        )
        
        
        
        
      }
    }
    
    Data_in<-Data_in%>% 
      mutate(Leaf_Area=as.double(Leaf_Area),NewValue=as.factor(NewValue))
    
    
    p<-ggplot()+
      theme_minimal()+
      theme(text=element_text(size=10,  family="DejaVu serif"),
            legend.text =element_text(size=8,  family="DejaVu serif"),
            legend.title =element_text(size=8,  family="DejaVu serif") )+
      scale_color_colorblind(labels = c('TREES', 'Experimental'))+
      labs(title = Figure_title,
           y=expression(paste("Leaf Area ("~cm^2~")" )),
           col = "Model")
    if(length(New_values)>1){
      p<-p+scale_color_colorblind(labels = c(New_values, 'Experimental'))
    }
    
    if(!is.null(Compare_to)){
      if(!Smooth_on){
        p<-p+geom_boxplot(data=filter(Compare_to,block==which(Drivers==i)),aes(x=Jday,y=Leaf_Area,group=Jday,color="Experimental Data"))
      }else{
        p<-p+geom_smooth(data=filter(Compare_to,block==which(Drivers==i)),aes(x=Jday,y=Leaf_Area,group=Leaf_number,color="Experimental Data"))
      }
    }
    
    
    if(Use_Gamma){
      if(!Smooth_on){
        Data_mod<-Data_in %>% 
          mutate(Jday=trunc(Jday))
        p<-p+geom_boxplot(data=Data_mod,aes(x=Jday,y=Leaf_Area,group=interaction(Leaf_number,NewValue,factor(Jday)),color=NewValue),alpha=0.5)
      }else{

        p<-p+geom_smooth(data=Data_in,aes(x=Jday,y=Leaf_Area,group=interaction(Leaf_number,NewValue),color=NewValue))
      }
    }else{
      p<-p+geom_line(data=Data_in,aes(x=Jday,y=Leaf_Area,group=interaction(Leaf_number,NewValue),color=NewValue))
    }
    
    
    
    ggsave(path=paste(Result_Dest,"/Figures",sep=""),filename=paste(i,Figure_title,".pdf",sep=""),plot=p,device=cairo_pdf,height=12,width=20,units = "cm")
    
    
  }
  
  
}



###Titles for y-axis for each sim output
Var_unit<-function(Which_Sim){
  Unit_vector<-c(simET=as.expression(bquote("Evapotranspiration mm "~s^-1)),
                  WPlant_K=as.expression(bquote("Plant hydraulic conductance mmol"~m^-2~s^-1~MPa^-1)),
                  Soil_Psi=as.expression(bquote(Psi[Soil]~"(MPa)" )),
                  Leaf_Psi=as.expression(bquote(Psi[Leaf]~"(MPa)" )),
                  Psi_Crit=as.expression(bquote(Psi[Crit]~"(MPa)" )),
                  Ecrit=as.expression(bquote("Critical transpiration mmol"~m^-2~s^-1)),
                  Ec=as.expression(bquote("Transpiration mmol"~m^-2~s^-1)),
                  RhizFlux0=as.expression(bquote("Rhizosphere flux 1 mmol"~m^-2~s^-1)),
                  RhizFlux1=as.expression(bquote("Rhizosphere flux 2 mmol"~m^-2~s^-1)),
                  RhizFlux2=as.expression(bquote("Rhizosphere flux 3 mmol"~m^-2~s^-1)),
                  RhizFlux3=as.expression(bquote("Rhizosphere flux 4 mmol"~m^-2~s^-1)),
                  Gs=as.expression(bquote("Stomatal conductance mol"~m^-2~s^-1)),
                  LAI=as.expression(bquote("LAI ("~m^2 ~m^-2~")" )),
                  SLA=as.expression(bquote("SLA ("~m^2 ~kgC^-1~")" )),
                  liveLAI=as.expression(bquote("Live LAI ("~m^2 ~m^-2~")" )),
                  Rmaint=as.expression(bquote("Maintenance respiration ("~kgC~ha^-1~")" )),
                  Rgrowth=as.expression(bquote("Growth respiration ("~kgC~ha^-1~")" )),
                  reproduction=as.expression(bquote("Reproduction (gC "~m^-2 ~")" )),
                  leafNSC=as.expression(bquote("Leaf Non-structural carbon ("~kgC~ha^-1~")" )),
                  stemNSC=as.expression(bquote("Stem Non-structural carbon ("~kgC~ha^-1~")" )),
                  rootNSC=as.expression(bquote("Root Non-structural carbon ("~kgC~ha^-1~")" )),
                  chloroStarch=as.expression(bquote("Chloro starch ("~kgC~ha^-1~")" )),
                  chloroSugar=as.expression(bquote("Chloro sugar ("~kgC~ha^-1~")" )),
                  waterStress=as.expression(bquote("Water Stress")),
                  litterH2O=as.expression(bquote("Litter water ("~m^3 ~m^-3~")")),
                  theta0=as.expression(bquote("Layer 0 soil water ("~m^3 ~m^-3~")")),
                  theta1=as.expression(bquote("Layer 1 soil water ("~m^3 ~m^-3~")")),
                  theta2=as.expression(bquote("Layer 2 soil water ("~m^3 ~m^-3~")")),
                  theta3=as.expression(bquote("Layer 3 soil water ("~m^3 ~m^-3~")")),
                  thetaRoot=as.expression(bquote("Average root water ("~m^3 ~m^-3~")")),
                  Can_Evap=as.expression(bquote("Free evap from wet canopy"~mm~s^-1)),
                  Snowpack="Snow pack m",
                  SnowEdef=as.expression(bquote("Snow energy deficit"~"°"~C^-1)),
                  Vcmax25=as.expression(bquote("Maximum carboxylation at 25 °C (μmol"~m^-2~s^-1~")")),
                  Vcmax_sun=as.expression(bquote("Leaf level Vcmax(sun) (μmol"~m^-2~s^-1~")")),
                  Vcmax_shd=as.expression(bquote("Leaf level Vcmax(shade) (μmol"~m^-2~s^-1~")")),
                  Jmax25=as.expression(bquote("Maximum J at 25 °C (μmol"~m^-2~s^-1~")")),
                  J_sun=as.expression(bquote("Leaf level J(sun) (μmol"~m^-2~s^-1~")")),
                  J_shd=as.expression(bquote("Leaf level J(sun) (μmol"~m^-2~s^-1~")")),
                  Asun=as.expression(bquote("Leaf level photosynthesis(sun) (μmol"~m^-2~s^-1~")")),
                  Ashd=as.expression(bquote("Leaf level photosynthesis(shade) (μmol"~m^-2~s^-1~")")),
                  Lsun=as.expression(bquote("Leaf level area(sun) ("~m^2 ~m^-2~")")),
                  Lshd=as.expression(bquote("Leaf level area(shade) ("~m^2 ~m^-2~")")),
                  Tsun=as.expression(bquote("Leaf level temperature (°C)")),
                  Tshd=as.expression(bquote("Leaf level temperature (°C)")),
                  Dsun=as.expression(bquote("Leaf(sun) VPD (kPa)")),
                  Dshd=as.expression(bquote("Leaf(sun) VPD (kPa)")),
                  Ci_sun=as.expression(bquote("Leaf level intercellular"~CO^2~"(sun) (ppm)")),
                  Ci_shd=as.expression(bquote("Leaf level intercellular"~CO^2~"(sun) (ppm)")),
                  PARsun=as.expression(bquote("Leaf level absorbed PAR(sun) (μmol"~m^-2~s^-1~")")),
                  PARshd=as.expression(bquote("Leaf level absorbed PAR(shade) (μmol"~m^-2~s^-1~")")),
                  gs_sun=as.expression(bquote("Leaf level stomatal conductance(sun) (mol"~m^-2~s^-1~")")),
                  gs_shd=as.expression(bquote("Leaf level stomatal conductance(sun) (mol"~m^-2~s^-1~")")),
                  NEE=as.expression(bquote("Net ecosystem exchange (μmol"~m^-2~s^-1~")")),
                  NPP=as.expression(bquote("Net primary production (μmol"~m^-2~s^-1~")")),
                  R_total=as.expression(bquote("Total respiration (μmol"~m^-2~s^-1~")")),
                  R_ag=as.expression(bquote("Above ground respiration (μmol"~m^-2~s^-1~")")),
                  R_bg=as.expression(bquote("Below ground respiration (μmol"~m^-2~s^-1~")")),
                  Rd_sun=as.expression(bquote("Dark respiration(sun) (μmol"~m^-2~s^-1~")")),
                  Rd_shd=as.expression(bquote("Dark respiration(shade) (μmol"~m^-2~s^-1~")")),
                  Csapwood=as.expression(bquote("Stem carbon ("~kgC~ha^-1~")")),
                  FibRootC0=as.expression(bquote("Root order 1 carbon content layer 0("~kgC~ha^-1~")")),
                  FibRootC1=as.expression(bquote("Root order 1 carbon content layer 1("~kgC~ha^-1~")")),
                  FibRootC2=as.expression(bquote("Root order 1 carbon content layer 2("~kgC~ha^-1~")")),
                  FibRootC3=as.expression(bquote("Root order 1 carbon content layer 3("~kgC~ha^-1~")")),
                  FineRootC0=as.expression(bquote("Root order 2 carbon content layer 0("~kgC~ha^-1~")")),
                  FineRootC1=as.expression(bquote("Root order 2 carbon content layer 1("~kgC~ha^-1~")")),
                  FineRootC2=as.expression(bquote("Root order 2 carbon content layer 2("~kgC~ha^-1~")")),
                  FineRootC3=as.expression(bquote("Root order 2 carbon content layer 3("~kgC~ha^-1~")")),
                  TotRootC0=as.expression(bquote("Total root carbon content layer 0("~kgC~ha^-1~")")),
                  TotRootC1=as.expression(bquote("Total root carbon content layer 1("~kgC~ha^-1~")")),
                  TotRootC2=as.expression(bquote("Total root carbon content layer 2("~kgC~ha^-1~")")),
                  TotRootC3=as.expression(bquote("Total root carbon content layer 3("~kgC~ha^-1~")")),
                  FineRootCN0=as.expression(bquote("Fine root CN layer 0("~kgC~kgN^-1~")")),
                  FineRootCN1=as.expression(bquote("Fine root CN layer 1("~kgC~kgN^-1~")")),
                  FineRootCN2=as.expression(bquote("Fine root CN layer 2("~kgC~kgN^-1~")")),
                  FineRootCN3=as.expression(bquote("Fine root CN layer 3("~kgC~kgN^-1~")")),
                  LeafCN=as.expression(bquote("Leaf CN ("~kgC~kgN^-1~")")),
                  humusC0=as.expression(bquote("Humus carbon content layer 0("~kgC~ha^-1~")")),
                  humusC1=as.expression(bquote("Humus carbon content layer 1("~kgC~ha^-1~")")),
                  humusC2=as.expression(bquote("Humus carbon content layer 2("~kgC~ha^-1~")")),
                  humusC3=as.expression(bquote("Humus carbon content layer 3("~kgC~ha^-1~")")),
                  RhizCl0=as.expression(bquote("Labile organic carbon content layer 0("~kgC~ha^-1~")")),
                  RhizCl1=as.expression(bquote("Labile organic carbon content layer 1("~kgC~ha^-1~")")),
                  RhizCl2=as.expression(bquote("Labile organic carbon content layer 2("~kgC~ha^-1~")")),
                  RhizCl3=as.expression(bquote("Labile organic carbon content layer 3("~kgC~ha^-1~")")),
                  RhizNl0=as.expression(bquote("Labile organic nitrogen content layer 0("~kgN~ha^-1~")")),
                  RhizNl1=as.expression(bquote("Labile organic nitrogen content layer 1("~kgN~ha^-1~")")),
                  RhizNl2=as.expression(bquote("Labile organic nitrogen content layer 2("~kgN~ha^-1~")")),
                  RhizNl3=as.expression(bquote("Labile organic nitrogen content layer 3("~kgN~ha^-1~")")),
                  AAexudateC0=as.expression(bquote("Amino acid content layer 0("~kgC~ha^-1~")")),
                  AAexudateC1=as.expression(bquote("Amino acid content layer 1("~kgC~ha^-1~")")),
                  AAexudateC2=as.expression(bquote("Amino acid content layer 2("~kgC~ha^-1~")")),
                  AAexudateC3=as.expression(bquote("Amino acid content layer 3("~kgC~ha^-1~")")),
                  SugarExudateC0=as.expression(bquote("Sugar exudate content layer 0("~kgC~ha^-1~")")),
                  SugarExudateC1=as.expression(bquote("Sugar exudate content layer 1("~kgC~ha^-1~")")),
                  SugarExudateC2=as.expression(bquote("Sugar exudate content layer 2("~kgC~ha^-1~")")),
                  SugarExudateC3=as.expression(bquote("Sugar exudate content layer 3("~kgC~ha^-1~")")),
                  MicrobC0=as.expression(bquote("Live microbial carbon layer 0("~kgC~ha^-1~")")),
                  MicrobC1=as.expression(bquote("Live microbial carbon layer 1("~kgC~ha^-1~")")),
                  MicrobC2=as.expression(bquote("Live microbial carbon layer 2("~kgC~ha^-1~")")),
                  MicrobC3=as.expression(bquote("Live microbial carbon layer 3("~kgC~ha^-1~")")),
                  MicrobN0=as.expression(bquote("Live microbial nitrogen layer 0("~kgN~ha^-1~")")),
                  MicrobN1=as.expression(bquote("Live microbial nitrogen layer 1("~kgN~ha^-1~")")),
                  MicrobN2=as.expression(bquote("Live microbial nitrogen layer 2("~kgN~ha^-1~")")),
                  MicrobN3=as.expression(bquote("Live microbial nitrogen layer 3("~kgN~ha^-1~")")),
                  "RhizN-"=as.expression(bquote("Rhizosphere nitrate content("~kgN~ha^-1~")")),
                  "RhizN+"=as.expression(bquote("Rhizosphere ammonium content("~kgN~ha^-1~")")),
                  PlantN=as.expression(bquote("Total plant nitrogen("~kgN~ha^-1~")")),
                  PlantNstat=as.expression(bquote("Plant N status")),
                  RLA=as.expression(bquote("Root to leaf area ("~m^2[root]~m^-2[leaf]~")")),
                  ar0=as.expression(bquote("Fraction of root area in layer 0 ("~m^2[rootlayer]~m^-2[totalroot])),
                  ar1=as.expression(bquote("Fraction of root area in layer 1 ("~m^2[rootlayer]~m^-2[totalroot])),
                  ar2=as.expression(bquote("Fraction of root area in layer 2 ("~m^2[rootlayer]~m^-2[totalroot])),
                  ar3=as.expression(bquote("Fraction of root area in layer 3 ("~m^2[rootlayer]~m^-2[totalroot]))
  )
  
  which_unit<-Unit_vector[Which_Sim]
  
  return(which_unit)
}
###############################################################################################################

########################################### Plot Sim_Value ####################################################


Sim_Plot<-function(Result_Dest=paste(getwd(),"/easyR_TREES/Outputs",sep=""),#Where TREES output results to.
                   Which_Sim=NULL,#Name of the variable in the .sim file exactly as it appears in the file.
                   Which_Parameter="microbiomeScalar",
                   New_values=c(1),
                   Use_Gamma=FALSE,
                   Itter=NULL,#number of iterations ran. (Only applies if Use_Gamma is TRUE)
                   Drivers="cc_ww_drivers_drought_validation",#Vector of driver names as characters
                   Figure_title=NULL,#Optional
                   Compare_to=NULL,#dataframe containing Jday, block, and the name of the sim variable you would like to plot.
                   Smooth_on=FALSE#Plot useing geom_smooth instead of boxplot? (TRUE or FALSE)
){
  
  
  #####################Create a matching function for units and match it to Which_Sim
  
  if(is.null(Figure_title)){
    Figure_title<-Which_Sim
  }
  if(is.null(New_values)){
    New_values<-0
  }
  if(is.null(Itter)){
    Itter<-0
  }
  
  dir.create(paste(Result_Dest,"/Figures",sep=""),recursive = T)
  
  for(i in Drivers){
    Data_in<- data.frame() 
    for(j in Itter){
      for(k in New_values){
        
        Data_in<-rbind(Data_in,
                       read_delim(paste(Result_Dest,"/",Which_Parameter,"/",i,"/",Which_Parameter,k,"itter",j,".sim",sep=""),"\t") %>% 
                         separate(col = ti, into = c("toss", "Jday","Hour","Min"),convert=TRUE)%>% 
                         mutate(Jday=Jday+((Hour+(Min/100))/24)) %>% 
                         dplyr::select(Jday,Which_Sim)  %>% 
                         mutate(NewValue=k,Itteration=j) %>% 
                         rename(Value=Which_Sim)
        )
        
        

      }
    }
    
    Data_in<-Data_in%>% 
      mutate(Which_Sim=as.double(Which_Sim),NewValue=as.factor(NewValue))
    
    
    p<-ggplot()+
      theme_minimal()+
      theme(text=element_text(size=10,  family="DejaVu serif"),
            legend.text =element_text(size=8,  family="DejaVu serif"),
            legend.title =element_text(size=8,  family="DejaVu serif") )+
      scale_color_colorblind(labels = c('TREES', 'Experimental'))+
      labs(title = Figure_title,
           y=Var_unit(Which_Sim = Which_Sim),
           col = "Model")
    if(length(New_values)>1){
      p<-p+scale_color_colorblind(labels = c(New_values, 'Experimental'))
    }
    
    if(!is.null(Compare_to)){
      if(!Smooth_on){
        p<-p+geom_boxplot(data=filter(Compare_to,block==which(Drivers==i)),aes(x=Jday,y=Value,group=Jday,color="Experimental Data"))
      }else{
        p<-p+geom_smooth(data=filter(Compare_to,block==which(Drivers==i)),aes(x=Jday,y=Value,color="Experimental Data"))
      }
    }
    
    
    if(Use_Gamma){
      if(!Smooth_on){
        Data_mod<-Data_in %>% 
          mutate(Jday=trunc(Jday))
        p<-p+geom_boxplot(data=Data_mod,aes(x=Jday,y=Value,group=interaction(NewValue,factor(Jday)),color=NewValue),alpha=0.5)
      }else{
        
        p<-p+geom_smooth(data=Data_in,aes(x=Jday,y=Value,group=NewValue,color=NewValue))
      }
    }else{
      p<-p+geom_line(data=Data_in,aes(x=Jday,y=Value,group=NewValue,color=NewValue))
    }
    
    
    
    ggsave(path=paste(Result_Dest,"/Figures",sep=""),
           filename=paste(i,Figure_title,".pdf",sep=""),
           plot=p,device=cairo_pdf,height=12,width=20,units = "cm")
    
    
  }
  
  
}

###############################################################################################################





